[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false
opt-level = "s" # Optimize for size even in debug builds

[profile.release]
incremental = false
codegen-units = 1
debug = true # Required for defmt
lto = false
opt-level = "s"

[profile.release.package.esp-radio]
opt-level = 3

[patch.crates-io]
# ariel-os embassy forks

# includes bt-hci 0.6.0 update
cyw43 = { git = "https://github.com/ariel-os/embassy", rev = "603583d9" }

# branch = "embassy-embedded-hal-v0.6.0+ariel-os"
embassy-embedded-hal = { git = "https://github.com/ariel-os/embassy", rev = "cae68deb86232f1026eb338734273fa7bd1790f4" }
# branch = "embassy-hal-internal-v0.5.0+ariel-os"
embassy-hal-internal = { git = "https://github.com/ariel-os/embassy", rev = "c7024cd2ee96f83d95f91570b2d445f95a222512" }
# branch = "embassy-net-v0.9.1+ariel-os": backport of https://github.com/embassy-rs/embassy/pull/6195
embassy-net = { git = "https://github.com/ariel-os/embassy", rev = "37683fe299f12028e5a77af9f742f496da08afcd" }
# branch = "embassy-nrf-v0.10.0+ariel-os"
embassy-nrf = { git = "https://github.com/ariel-os/embassy", rev = "791f31c20e3e0edea2a91024903993b32ee74873" }
# branch = "embassy-rp-v0.10.0+ariel-os"
embassy-rp = { git = "https://github.com/ariel-os/embassy", rev = "0bee931086e431ea2d7923257d84eb018a43e554" }
# branch = "embassy-stm32-v0.6.0+ariel-os"
embassy-stm32 = { git = "https://github.com/ariel-os/embassy", rev = "2bce2a9816bad68e3d4b8ecb1b746c6d3810d647" }
# branch = "embassy-time-v0.5.1+ariel-os"
embassy-time = { git = "https://github.com/ariel-os/embassy", rev = "3c1b5fbf28237ea7144ae970c3aec11c38023c3f" }

# ariel-os esp-hal fork, using branch = "esp-hal-v1.0.0+20251203+ariel-os"
esp-alloc = { git = "https://github.com/ariel-os/esp-hal", rev = "531c629afdd80ea464682ce7f4db8baed97967a6" }
esp-bootloader-esp-idf = { git = "https://github.com/ariel-os/esp-hal", rev = "531c629afdd80ea464682ce7f4db8baed97967a6" }
esp-hal = { git = "https://github.com/ariel-os/esp-hal", rev = "531c629afdd80ea464682ce7f4db8baed97967a6" }
esp-metadata-generated = { git = "https://github.com/ariel-os/esp-hal", rev = "531c629afdd80ea464682ce7f4db8baed97967a6" }
esp-println = { git = "https://github.com/ariel-os/esp-hal", rev = "531c629afdd80ea464682ce7f4db8baed97967a6" }
esp-radio = { git = "https://github.com/ariel-os/esp-hal", rev = "531c629afdd80ea464682ce7f4db8baed97967a6" }
esp-radio-rtos-driver = { git = "https://github.com/ariel-os/esp-hal", rev = "531c629afdd80ea464682ce7f4db8baed97967a6" }
esp-rom-sys = { git = "https://github.com/ariel-os/esp-hal", rev = "531c629afdd80ea464682ce7f4db8baed97967a6" }
esp-sync = { git = "https://github.com/ariel-os/esp-hal", rev = "531c629afdd80ea464682ce7f4db8baed97967a6" }
xtensa-lx-rt = { git = "https://github.com/ariel-os/esp-hal", rev = "531c629afdd80ea464682ce7f4db8baed97967a6" }
