[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false
opt-level = "s"     # Optimize for size even in debug builds

[profile.release]
incremental = false
codegen-units = 1
debug = true        # Required for defmt
lto = false
opt-level = "s"

[profile.release.package.esp-wifi]
opt-level = 3

[patch.crates-io]
# ariel-os embassy forks
embassy-embedded-hal = { git = "https://github.com/ariel-os/embassy", branch = "embassy-embedded-hal-v0.3.0+ariel-os" }
embassy-executor = { git = "https://github.com/ariel-os/embassy", branch = "embassy-executor-v0.7.0+ariel-os" }
embassy-hal-internal = { git = "https://github.com/ariel-os/embassy", branch = "embassy-hal-internal-v0.2.0+ariel-os" }
embassy-nrf = { git = "https://github.com/ariel-os/embassy", branch = "embassy-nrf-v0.3.1+ariel-os" }
#embassy-net = { git = "https://github.com/ariel-os/embassy", branch = "embassy-net-v0.6.0+ariel-os+slaac" }
embassy-net = { path = "/home/kaspar/src/embassy/embassy-net" }
embassy-rp = { git = "https://github.com/ariel-os/embassy", branch = "embassy-rp-v0.3.0+ariel-os" }
embassy-stm32 = { git = "https://github.com/ariel-os/embassy", branch = "embassy-stm32-v0.2.0+ariel-os" }

# ariel-os esp-hal fork
esp-alloc = { git = "https://github.com/ariel-os/esp-hal", branch = "v0.23.1+ariel-os" }
esp-hal = { git = "https://github.com/ariel-os/esp-hal", branch = "v0.23.1+ariel-os" }
esp-hal-embassy = { git = "https://github.com/ariel-os/esp-hal", branch = "v0.23.1+ariel-os" }
esp-println = { git = "https://github.com/ariel-os/esp-hal", branch = "v0.23.1+ariel-os" }
esp-wifi = { git = "https://github.com/ariel-os/esp-hal", branch = "v0.23.1+ariel-os" }
esp-storage = { git = "https://github.com/ariel-os/esp-hal", branch = "v0.23.1+ariel-os" }
xtensa-lx-rt = { git = "https://github.com/ariel-os/esp-hal", branch = "v0.23.1+ariel-os" }

# patched to use portable-atomics <https://github.com/seanmonstar/try-lock/pull/11>
try-lock = { git = "https://github.com/seanmonstar/try-lock", rev = "a1aadfac9840fe23672159c12af7272e44bc684c" }

# added Ariel OS support
embedded-test = { git = "https://github.com/ariel-os/embedded-test", branch = "v0.6.0+ariel-os" }

# see src/lib/coapcore/Cargo.toml: Support for negative integers <https://github.com/twittner/minicbor/pull/9>
minicbor = { git = "https://github.com/chrysn-pull-requests/minicbor", branch = "negativ-indices" }
